import type { NextPage } from 'next';
import Script from 'next/script'
import Head from 'next/head';
import { Col, Row, Typography, List, Divider, Space } from 'antd';
import Layout, { Content, Footer, Header } from 'antd/lib/layout/layout';
import {
	PhoneOutlined,
	MailOutlined,
	ClockCircleOutlined,
} from '@ant-design/icons';

const { Title, Text, Paragraph } = Typography;

const serviceData = [
  'ศูนย์บริการยางครบวงจร',
  'บริการตรวจเช็คสภาพรถยนต์',
  'เบรค',
  'โช๊คอัพ',
	'ใส้กรอง',
];

const socialData = [{
	name: 'ststyrecenter',
	linkIcon: '/img/fb-icon.webp',
	link: 'https://www.facebook.com/ststyrecenter',
}, {
	name: 'LINE',
	linkIcon: '/img/line-icon.webp',
	link: 'http://line.me/ti/p/@lbb2631z',
	}]

const brandData = [{
	name: 'YOKOHAMA',
	linkIcon: '/img/logo/yokohama.webp',
}, {
	name: 'GOOD YEAR',
	linkIcon: '/img/logo/good-year.webp',
}, {
	name: 'MICHELIN',
	linkIcon: '/img/logo/michelin.webp',
}, {
	name: 'BRIDGESTONE',
	linkIcon: '/img/logo/bridgestone.webp',
}, {
	name: 'MAXXIS',
	linkIcon: '/img/logo/maxxis.webp',
}, {
	name: 'FLAKEN',
	linkIcon: '/img/logo/flaken.webp',
}, {
	name: 'Castrol',
	linkIcon: '/img/logo/castrol.webp',
}, {
	name: 'TOKICO',
	linkIcon: '/img/logo/tokico.webp',
}, {
	name: 'LENSO',
	linkIcon: '/img/logo/lenso.webp',
	}];

const headerTitle = `ศูนย์ยางรถยนต์ STS เอกชัย บางบอน
	บริการทุกระดับประทับใจ มีปัญหาเรื่องรถ เรื่องยาง ยินดีให้คำปรึกษา`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>
          ศูนย์ยางรถยนต์ STS เอกชัย บางบอน | STS SMART TYRE SERVICE CO., LTD.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/img/fav/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/img/fav/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/img/fav/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/img/fav/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/img/fav/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/img/fav/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/img/fav/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/img/fav/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/img/fav/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/img/fav/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/img/fav/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/img/fav/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/img/fav/favicon-16x16.png"
        />
        <link rel="manifest" href="/img/fav/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>
      <Layout>
        <div id="fb-root"></div>
        <Script
          async
          defer
          crossOrigin="anonymous"
          src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v13.0&appId=1328409690926518&autoLogAppEvents=1"
          nonce="wabGnawZ"
        ></Script>
        <Header>
          <Row align="middle">
            <Col xs={24} sm={4} md={4}>
              <Title
                level={1}
                className="text-center"
                style={{ marginBottom: 0 }}
              >
                <img
                  src="/img/fav/ms-icon-310x310.png"
                  alt="STS SMART TYRE SERVICE CO., LTD."
                  className="logo"
                />
              </Title>
            </Col>
            <Col xs={24} sm={24} md={10}>
              <Title level={3} className="title-desc">
                ศูนย์ยางรถยนต์ STS เอกชัย บางบอน
                <br />
                บริการทุกระดับประทับใจ มีปัญหาเรื่องรถ เรื่องยาง
                ยินดีให้คำปรึกษา
              </Title>
            </Col>
            <Col xs={24} sm={24} md={10}>
              <Text className="color-red">
                เราเป็นตัวแทน Yokohama Club Network สาขาที่ 49
              </Text>
              <p>
                <img
                  src="/img/logo/yokohama-club-network.png"
                  width="320"
                  style={{ maxWidth: '500px' }}
                />
              </p>
            </Col>
          </Row>
        </Header>

        <Content>
          <Row className="main-section section">
            <Col xs={24} sm={12} md={12} className="text-center">
              <img
                src="/img/promotion/promo-bank-credit.webp"
                className="img-responsive"
                style={{ marginBottom: '1rem' }}
              />
            </Col>
            <Col xs={24} sm={12} md={12}>
              <iframe
                className="video-stream"
                title="STS SMART TYRE SERVICE CO., LTD."
                src="https://www.youtube.com/embed/e_8B0GAvOGw?list=TLGGdS9jyVYqIO8yNDA0MjAyMg&autoplay=1&loop=1"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </Col>
          </Row>
          <Row className="service-detail-section section bg-red">
            <Col xs={24} sm={12} md={14}>
              <Title level={2} className="p-title color-white">
                ศูนย์บริการยางครบวงจร
              </Title>
              <Paragraph
                className="color-white p-content"
                style={{ maxWidth: '500px' }}
              >
                บริการยางรถยนต์ทุกยี่ห้อชั้นนำ Yokohama Michelin Bridgestone
                Dunlop Goodyear Nexen GTRadial Maxxis และ
                ยี่ห้อชั้นนำอีกหลากหลาย
              </Paragraph>

              <Title level={2} className="p-title color-white">
                อุปกรณ์อะไหล่รถยนต์
              </Title>
              <Paragraph
                className="color-white p-content"
                style={{ maxWidth: '500px' }}
              >
                บริการยางรถยนต์ทุกยี่ห้อชั้นนำ Yokohama Michelin Bridgestone
                Dunlop Goodyear Nexen GTRadial Maxxis และ
                ยี่ห้อชั้นนำอีกหลากหลาย
              </Paragraph>

              <Title level={2} className="p-title color-white">
                บริการตรวจเช็คสภาพรถยนต์
              </Title>
              <Paragraph
                className="color-white p-content"
                style={{ maxWidth: '500px' }}
              >
                บริการยางรถยนต์ทุกยี่ห้อชั้นนำ Yokohama Michelin Bridgestone
                Dunlop Goodyear Nexen GTRadial Maxxis และ
                ยี่ห้อชั้นนำอีกหลากหลาย
              </Paragraph>
            </Col>
            <Col xs={24} sm={12} md={10}>
              <div id="fb-root"></div>
              <div
                className="fb-page"
                data-href="https://www.facebook.com/ststyrecenter"
                data-tabs="timeline"
                data-width="500"
                data-height="800"
                data-small-header="false"
                data-adapt-container-width="true"
                data-hide-cover="false"
                data-show-facepile="true"
              >
                <blockquote
                  cite="https://www.facebook.com/ststyrecenter"
                  className="fb-xfbml-parse-ignore"
                >
                  <a href="https://www.facebook.com/ststyrecenter">
                    ศูนย์ยางรถยนต์ STS เอกชัย บางบอน
                  </a>
                </blockquote>
              </div>
            </Col>
          </Row>

          <Row
            className="brand-section section"
            id="brand-section"
            align="middle"
          >
            <Col span={24}>
              <Title level={2}>สินค้าแบรนด์คุณภาพ</Title>
            </Col>
            {brandData.map((item) => {
              return (
                <Col xs={12} sm={12} md={8} key={`brand-${item.name}`}>
                  <img src={item.linkIcon} width="320" className="img-brand" />
                </Col>
              );
            })}
          </Row>
          <Row className="contactus-section section" id="contactus-section">
            <Col xs={24} sm={24} md={8}>
              <Title level={3} className="color-white">
                <PhoneOutlined /> โทร
              </Title>
              <Paragraph className="color-white">
                <Space size={'small'} split={<Divider type="vertical" />}>
                  <a href="tel:0925369151" className="color-white">
                    092-536-9151
                  </a>
                  <a href="tel:0961499969" className="color-white">
                    096-149-9969
                  </a>
                </Space>
              </Paragraph>
            </Col>
            <Col xs={24} sm={24} md={8}>
              <Title level={3} className="color-white">
                <MailOutlined /> EMAIL
              </Title>
              <Paragraph className="color-white">
                <a
                  href="mailto:sts.smarttyreservice@gmail.com"
                  className="color-white"
                >
                  sts.smarttyreservice@gmail.com
                </a>
              </Paragraph>
            </Col>
            <Col xs={24} sm={24} md={8}>
              <Title level={3} className="color-white">
                <ClockCircleOutlined /> เวลาทำการ
              </Title>
              <Paragraph className="color-white">
                จันทร์ - เสาร์ : 8.00 น. - 18.00 น.
              </Paragraph>
            </Col>
          </Row>
        </Content>

        <Footer>
          <Row className="social-media-section section">
            <Col xs={24} sm={24} md={8}>
              <Title level={4} className="color-white">
                Social Media
              </Title>
              <List
                className="color-white"
                dataSource={socialData}
                split={false}
                renderItem={(item) => (
                  <List.Item>
                    <a
                      href={item.link}
                      target="_blank"
                      rel="noreferrer"
                      className="color-white"
                    >
                      <img src={item.linkIcon} />
                      &nbsp;&nbsp;&nbsp;{item.name}
                    </a>
                  </List.Item>
                )}
              />
            </Col>
            <Col xs={24} sm={24} md={8} id="service-section">
              <Title level={4} className="color-white">
                บริการของเรา
              </Title>
              <List
                className="color-white"
                dataSource={serviceData}
                split={false}
                renderItem={(item) => <List.Item> - {item}</List.Item>}
              />
            </Col>
            <Col xs={24} sm={24} md={8} id="address-section">
              <Title level={4} className="color-white">
                ที่อยู่
              </Title>
              <Text className="color-white">{`อาคารเลขที่ 59 ซอยเอกชัย 83/1
							(พระราม 2 ซอย 54) แขวงคลองบางบอน เขตบางบอน กรุงเทพมหานคร`}</Text>
            </Col>
            <Col xs={24} span={24} className="copyright text-center">
              &copy; 2018 by STS SMART TYRE SERVICE CO., LTD.
            </Col>
          </Row>
        </Footer>
      </Layout>
    </>
  );
};

export default Home;
